### ISSUE TITLE
Wrong xslthl-config.xml used

### ISSUE THREAD

**Issue by jvalkeal** [spring-gradle-plugins/docbook-reference-plugin#2]
I'm not able to get code highlighting work with `groovy` and `yaml`. This seems to be caused by task using a wrong `xslthl-config.xml` file. 

```
Executing task ':referenceHtmlSingle' (up-to-date check took 0.003 secs) due to:
  Output file /home/jvalkealahti/repos/jvalkeal/spring-hadoop-docs/build/reference has changed.
  Output file /home/jvalkealahti/repos/jvalkeal/spring-hadoop-docs/build/reference/htmlsingle/images/callouts/4.gif has been removed.
  Output file /home/jvalkealahti/repos/jvalkeal/spring-hadoop-docs/build/reference/htmlsingle/images/up.png has been removed.
Note: namesp. cut : stripped namespace before processing           Spring for Apache Hadoop - Reference Documentation
Note: namesp. cut : processing stripped document                   Spring for Apache Hadoop - Reference Documentation
Loading Xslthl configuration from file:/home/jvalkealahti/repos/jvalkeal/spring-hadoop-docs/build/docbook-resources/highlighting/xslthl-config.xml...
:referenceHtmlSingle (Thread[main,5,main]) completed. Took 4.392 secs.
```

I believe it should load `/home/jvalkealahti/repos/jvalkeal/spring-hadoop-docs/build/docbook-resources/xsl/xslthl-config.xml` instead.

Boot is using maven plugins and defines these files manually which is not an option, afaik, for gradle. Also it looks like framework core docs also doesn't highlight groovy sources (i.e. Groovy Bean Definition DSL section).

**Comment by rwinch** [comment]
Thanks for the report @jvalkeal! This is now fixed in 0.3.1 (which is now released)
